# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class AuthenticatorFlowElementSsoOptionsToken(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Token.
    """


    class MetaOapg:
        
        class properties:
            
            
            class EncryptionMethod(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "3DES": "_3DES",
                        "AES128": "AES128",
                        "BLOWFISH": "BLOWFISH",
                    }
                
                @schemas.classproperty
                def _3DES(cls):
                    return cls("3DES")
                
                @schemas.classproperty
                def AES128(cls):
                    return cls("AES128")
                
                @schemas.classproperty
                def BLOWFISH(cls):
                    return cls("BLOWFISH")
            Key = schemas.StrSchema
            Leeway = schemas.IntSchema
            
            
            class MacMethod(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "md5": "MD5",
                        "MD5": "MD5",
                        "sha1": "SHA1",
                        "sha256": "SHA256",
                        "sha512": "SHA512",
                    }
                
                @schemas.classproperty
                def MD5(cls):
                    return cls("md5")
                
                @schemas.classproperty
                def MD5(cls):
                    return cls("MD5")
                
                @schemas.classproperty
                def SHA1(cls):
                    return cls("sha1")
                
                @schemas.classproperty
                def SHA256(cls):
                    return cls("sha256")
                
                @schemas.classproperty
                def SHA512(cls):
                    return cls("sha512")
            
            
            class BlockCipher(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "CBC": "CBC",
                        "ECB": "ECB",
                    }
                
                @schemas.classproperty
                def CBC(cls):
                    return cls("CBC")
                
                @schemas.classproperty
                def ECB(cls):
                    return cls("ECB")
            __annotations__ = {
                "EncryptionMethod": EncryptionMethod,
                "Key": Key,
                "Leeway": Leeway,
                "MacMethod": MacMethod,
                "BlockCipher": BlockCipher,
            }
        additional_properties = schemas.AnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EncryptionMethod"]) -> MetaOapg.properties.EncryptionMethod: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Key"]) -> MetaOapg.properties.Key: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Leeway"]) -> MetaOapg.properties.Leeway: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["MacMethod"]) -> MetaOapg.properties.MacMethod: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["BlockCipher"]) -> MetaOapg.properties.BlockCipher: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["EncryptionMethod"], typing_extensions.Literal["Key"], typing_extensions.Literal["Leeway"], typing_extensions.Literal["MacMethod"], typing_extensions.Literal["BlockCipher"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EncryptionMethod"]) -> typing.Union[MetaOapg.properties.EncryptionMethod, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Key"]) -> typing.Union[MetaOapg.properties.Key, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Leeway"]) -> typing.Union[MetaOapg.properties.Leeway, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["MacMethod"]) -> typing.Union[MetaOapg.properties.MacMethod, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["BlockCipher"]) -> typing.Union[MetaOapg.properties.BlockCipher, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["EncryptionMethod"], typing_extensions.Literal["Key"], typing_extensions.Literal["Leeway"], typing_extensions.Literal["MacMethod"], typing_extensions.Literal["BlockCipher"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        EncryptionMethod: typing.Union[MetaOapg.properties.EncryptionMethod, str, schemas.Unset] = schemas.unset,
        Key: typing.Union[MetaOapg.properties.Key, str, schemas.Unset] = schemas.unset,
        Leeway: typing.Union[MetaOapg.properties.Leeway, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        MacMethod: typing.Union[MetaOapg.properties.MacMethod, str, schemas.Unset] = schemas.unset,
        BlockCipher: typing.Union[MetaOapg.properties.BlockCipher, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'AuthenticatorFlowElementSsoOptionsToken':
        return super().__new__(
            cls,
            *args,
            EncryptionMethod=EncryptionMethod,
            Key=Key,
            Leeway=Leeway,
            MacMethod=MacMethod,
            BlockCipher=BlockCipher,
            _configuration=_configuration,
            **kwargs,
        )
