# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class BlockRandomizerFlowElement(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Block randomizer flow.
    """


    class MetaOapg:
        
        class properties:
            
            
            class Type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "BlockRandomizer": "BLOCK_RANDOMIZER",
                    }
                
                @schemas.classproperty
                def BLOCK_RANDOMIZER(cls):
                    return cls("BlockRandomizer")
        
            @staticmethod
            def FlowID() -> typing.Type['FlowID']:
                return FlowID
            SubSet = schemas.IntSchema
            EvenPresentation = schemas.BoolSchema
        
            @staticmethod
            def Flow() -> typing.Type['Flow']:
                return Flow
            __annotations__ = {
                "Type": Type,
                "FlowID": FlowID,
                "SubSet": SubSet,
                "EvenPresentation": EvenPresentation,
                "Flow": Flow,
            }
        additional_properties = schemas.AnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Type"]) -> MetaOapg.properties.Type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["FlowID"]) -> 'FlowID': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SubSet"]) -> MetaOapg.properties.SubSet: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EvenPresentation"]) -> MetaOapg.properties.EvenPresentation: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Flow"]) -> 'Flow': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Type"], typing_extensions.Literal["FlowID"], typing_extensions.Literal["SubSet"], typing_extensions.Literal["EvenPresentation"], typing_extensions.Literal["Flow"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Type"]) -> typing.Union[MetaOapg.properties.Type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["FlowID"]) -> typing.Union['FlowID', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SubSet"]) -> typing.Union[MetaOapg.properties.SubSet, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EvenPresentation"]) -> typing.Union[MetaOapg.properties.EvenPresentation, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Flow"]) -> typing.Union['Flow', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Type"], typing_extensions.Literal["FlowID"], typing_extensions.Literal["SubSet"], typing_extensions.Literal["EvenPresentation"], typing_extensions.Literal["Flow"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        Type: typing.Union[MetaOapg.properties.Type, str, schemas.Unset] = schemas.unset,
        FlowID: typing.Union['FlowID', schemas.Unset] = schemas.unset,
        SubSet: typing.Union[MetaOapg.properties.SubSet, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        EvenPresentation: typing.Union[MetaOapg.properties.EvenPresentation, bool, schemas.Unset] = schemas.unset,
        Flow: typing.Union['Flow', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'BlockRandomizerFlowElement':
        return super().__new__(
            cls,
            *args,
            Type=Type,
            FlowID=FlowID,
            SubSet=SubSet,
            EvenPresentation=EvenPresentation,
            Flow=Flow,
            _configuration=_configuration,
            **kwargs,
        )

from qualtrics_survey_python_sdk.model.flow import Flow
from qualtrics_survey_python_sdk.model.flow_id import FlowID
