# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class CustomValidation(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Additional validation to direct respondents to answer questions in a certain way.
    """


    class MetaOapg:
        required = {
            "Message",
            "Logic",
        }
        
        class properties:
        
            @staticmethod
            def Logic() -> typing.Type['BranchLogic']:
                return BranchLogic
        
            @staticmethod
            def Message() -> typing.Type['CustomValidationMessage']:
                return CustomValidationMessage
            __annotations__ = {
                "Logic": Logic,
                "Message": Message,
            }
        additional_properties = schemas.AnyTypeSchema
    
    Message: 'CustomValidationMessage'
    Logic: 'BranchLogic'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Message"]) -> 'CustomValidationMessage': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Logic"]) -> 'BranchLogic': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Message"], typing_extensions.Literal["Logic"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Message"]) -> 'CustomValidationMessage': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Logic"]) -> 'BranchLogic': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Message"], typing_extensions.Literal["Logic"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        Message: 'CustomValidationMessage',
        Logic: 'BranchLogic',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'CustomValidation':
        return super().__new__(
            cls,
            *args,
            Message=Message,
            Logic=Logic,
            _configuration=_configuration,
            **kwargs,
        )

from qualtrics_survey_python_sdk.model.branch_logic import BranchLogic
from qualtrics_survey_python_sdk.model.custom_validation_message import CustomValidationMessage
