# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class EmbeddedDataFlowElement(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Embedded data flow element.
    """


    class MetaOapg:
        
        class properties:
            
            
            class Type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def EMBEDDED_DATA(cls):
                    return cls("EmbeddedData")
        
            @staticmethod
            def FlowID() -> typing.Type['FlowID']:
                return FlowID
        
            @staticmethod
            def EmbeddedData() -> typing.Type['EmbeddedDataFlowElementEmbeddedData']:
                return EmbeddedDataFlowElementEmbeddedData
            __annotations__ = {
                "Type": Type,
                "FlowID": FlowID,
                "EmbeddedData": EmbeddedData,
            }
        additional_properties = schemas.AnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Type"]) -> MetaOapg.properties.Type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["FlowID"]) -> 'FlowID': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EmbeddedData"]) -> 'EmbeddedDataFlowElementEmbeddedData': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Type"], typing_extensions.Literal["FlowID"], typing_extensions.Literal["EmbeddedData"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Type"]) -> typing.Union[MetaOapg.properties.Type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["FlowID"]) -> typing.Union['FlowID', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EmbeddedData"]) -> typing.Union['EmbeddedDataFlowElementEmbeddedData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Type"], typing_extensions.Literal["FlowID"], typing_extensions.Literal["EmbeddedData"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        Type: typing.Union[MetaOapg.properties.Type, str, schemas.Unset] = schemas.unset,
        FlowID: typing.Union['FlowID', schemas.Unset] = schemas.unset,
        EmbeddedData: typing.Union['EmbeddedDataFlowElementEmbeddedData', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'EmbeddedDataFlowElement':
        return super().__new__(
            cls,
            *args,
            Type=Type,
            FlowID=FlowID,
            EmbeddedData=EmbeddedData,
            _configuration=_configuration,
            **kwargs,
        )

from qualtrics_survey_python_sdk.model.embedded_data_flow_element_embedded_data import EmbeddedDataFlowElementEmbeddedData
from qualtrics_survey_python_sdk.model.flow_id import FlowID
