# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class FlowType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Type of flow element. One of `Authenticator`, `Block`, `BlockRandomizer`, `Branch`, `Conjoint`, `EmbeddedData`, `EndSurvey`, `Group`, `QuotaCheck`, `ReferenceSurvey`, `Root`, `Standard`, `SupplementalData`, `TableOfContents`, `WebService`
    """


    class MetaOapg:
        enum_value_to_name = {
            "Authenticator": "AUTHENTICATOR",
            "Block": "BLOCK",
            "BlockRandomizer": "BLOCK_RANDOMIZER",
            "Branch": "BRANCH",
            "Conjoint": "CONJOINT",
            "EmbeddedData": "EMBEDDED_DATA",
            "EndSurvey": "END_SURVEY",
            "Group": "GROUP",
            "QuotaCheck": "QUOTA_CHECK",
            "ReferenceSurvey": "REFERENCE_SURVEY",
            "Root": "ROOT",
            "Standard": "STANDARD",
            "SupplementalData": "SUPPLEMENTAL_DATA",
            "TableOfContents": "TABLE_OF_CONTENTS",
            "WebService": "WEB_SERVICE",
        }
    
    @schemas.classproperty
    def AUTHENTICATOR(cls):
        return cls("Authenticator")
    
    @schemas.classproperty
    def BLOCK(cls):
        return cls("Block")
    
    @schemas.classproperty
    def BLOCK_RANDOMIZER(cls):
        return cls("BlockRandomizer")
    
    @schemas.classproperty
    def BRANCH(cls):
        return cls("Branch")
    
    @schemas.classproperty
    def CONJOINT(cls):
        return cls("Conjoint")
    
    @schemas.classproperty
    def EMBEDDED_DATA(cls):
        return cls("EmbeddedData")
    
    @schemas.classproperty
    def END_SURVEY(cls):
        return cls("EndSurvey")
    
    @schemas.classproperty
    def GROUP(cls):
        return cls("Group")
    
    @schemas.classproperty
    def QUOTA_CHECK(cls):
        return cls("QuotaCheck")
    
    @schemas.classproperty
    def REFERENCE_SURVEY(cls):
        return cls("ReferenceSurvey")
    
    @schemas.classproperty
    def ROOT(cls):
        return cls("Root")
    
    @schemas.classproperty
    def STANDARD(cls):
        return cls("Standard")
    
    @schemas.classproperty
    def SUPPLEMENTAL_DATA(cls):
        return cls("SupplementalData")
    
    @schemas.classproperty
    def TABLE_OF_CONTENTS(cls):
        return cls("TableOfContents")
    
    @schemas.classproperty
    def WEB_SERVICE(cls):
        return cls("WebService")
