# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class KeyValuePairArray(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['KeyValuePairArrayItem']:
            return KeyValuePairArrayItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['KeyValuePairArrayItem'], typing.List['KeyValuePairArrayItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'KeyValuePairArray':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'KeyValuePairArrayItem':
        return super().__getitem__(i)

from qualtrics_survey_python_sdk.model.key_value_pair_array_item import KeyValuePairArrayItem
