# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class ProjectInfoDefinitionContentBundle(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "RegistrySha",
            "SurveyInputVariables",
            "BundleShortName",
            "RegistryVersion",
        }
        
        class properties:
            
            
            class BundleShortName(
                schemas.StrSchema
            ):
                pass
            
            
            class RegistrySha(
                schemas.StrSchema
            ):
                pass
            
            
            class RegistryVersion(
                schemas.StrSchema
            ):
                pass
        
            @staticmethod
            def SurveyInputVariables() -> typing.Type['ProjectInfoDefinitionContentBundleSurveyInputVariables']:
                return ProjectInfoDefinitionContentBundleSurveyInputVariables
            __annotations__ = {
                "BundleShortName": BundleShortName,
                "RegistrySha": RegistrySha,
                "RegistryVersion": RegistryVersion,
                "SurveyInputVariables": SurveyInputVariables,
            }
        additional_properties = schemas.AnyTypeSchema
    
    RegistrySha: MetaOapg.properties.RegistrySha
    SurveyInputVariables: 'ProjectInfoDefinitionContentBundleSurveyInputVariables'
    BundleShortName: MetaOapg.properties.BundleShortName
    RegistryVersion: MetaOapg.properties.RegistryVersion
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["RegistrySha"]) -> MetaOapg.properties.RegistrySha: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SurveyInputVariables"]) -> 'ProjectInfoDefinitionContentBundleSurveyInputVariables': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["BundleShortName"]) -> MetaOapg.properties.BundleShortName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["RegistryVersion"]) -> MetaOapg.properties.RegistryVersion: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["RegistrySha"], typing_extensions.Literal["SurveyInputVariables"], typing_extensions.Literal["BundleShortName"], typing_extensions.Literal["RegistryVersion"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["RegistrySha"]) -> MetaOapg.properties.RegistrySha: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SurveyInputVariables"]) -> 'ProjectInfoDefinitionContentBundleSurveyInputVariables': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["BundleShortName"]) -> MetaOapg.properties.BundleShortName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["RegistryVersion"]) -> MetaOapg.properties.RegistryVersion: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["RegistrySha"], typing_extensions.Literal["SurveyInputVariables"], typing_extensions.Literal["BundleShortName"], typing_extensions.Literal["RegistryVersion"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        RegistrySha: typing.Union[MetaOapg.properties.RegistrySha, str, ],
        SurveyInputVariables: 'ProjectInfoDefinitionContentBundleSurveyInputVariables',
        BundleShortName: typing.Union[MetaOapg.properties.BundleShortName, str, ],
        RegistryVersion: typing.Union[MetaOapg.properties.RegistryVersion, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'ProjectInfoDefinitionContentBundle':
        return super().__new__(
            cls,
            *args,
            RegistrySha=RegistrySha,
            SurveyInputVariables=SurveyInputVariables,
            BundleShortName=BundleShortName,
            RegistryVersion=RegistryVersion,
            _configuration=_configuration,
            **kwargs,
        )

from qualtrics_survey_python_sdk.model.project_info_definition_content_bundle_survey_input_variables import ProjectInfoDefinitionContentBundleSurveyInputVariables
