# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class QuestionConfiguration(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Configurations for how the question should be displayed
    """


    class MetaOapg:
        
        class properties:
            
            
            class QuestionDescriptionOption(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def USE_TEXT(cls):
                    return cls("UseText")
                
                @schemas.classproperty
                def SPECIFY_LABEL(cls):
                    return cls("SpecifyLabel")
            
            
            class TextPosition(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def INLINE(cls):
                    return cls("inline")
            
            
            class ChoiceColumnWidth(
                schemas.EnumBase,
                schemas.IntSchema
            ):
                
                @schemas.classproperty
                def POSITIVE_25(cls):
                    return cls(25)
            
            
            class RepeatHeaders(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def NONE(cls):
                    return cls("none")
            
            
            class WhiteSpace(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def TRUE(cls):
                    return cls("true")
                
                @schemas.classproperty
                def FALSE(cls):
                    return cls("false")
            
            
            class LabelPosition(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def BELOW(cls):
                    return cls("BELOW")
                
                @schemas.classproperty
                def SIDE(cls):
                    return cls("SIDE")
            NumColumns = schemas.IntSchema
            MobileFirst = schemas.BoolSchema
            __annotations__ = {
                "QuestionDescriptionOption": QuestionDescriptionOption,
                "TextPosition": TextPosition,
                "ChoiceColumnWidth": ChoiceColumnWidth,
                "RepeatHeaders": RepeatHeaders,
                "WhiteSpace": WhiteSpace,
                "LabelPosition": LabelPosition,
                "NumColumns": NumColumns,
                "MobileFirst": MobileFirst,
            }
        additional_properties = schemas.AnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["QuestionDescriptionOption"]) -> MetaOapg.properties.QuestionDescriptionOption: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["TextPosition"]) -> MetaOapg.properties.TextPosition: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ChoiceColumnWidth"]) -> MetaOapg.properties.ChoiceColumnWidth: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["RepeatHeaders"]) -> MetaOapg.properties.RepeatHeaders: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["WhiteSpace"]) -> MetaOapg.properties.WhiteSpace: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LabelPosition"]) -> MetaOapg.properties.LabelPosition: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["NumColumns"]) -> MetaOapg.properties.NumColumns: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["MobileFirst"]) -> MetaOapg.properties.MobileFirst: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["QuestionDescriptionOption"], typing_extensions.Literal["TextPosition"], typing_extensions.Literal["ChoiceColumnWidth"], typing_extensions.Literal["RepeatHeaders"], typing_extensions.Literal["WhiteSpace"], typing_extensions.Literal["LabelPosition"], typing_extensions.Literal["NumColumns"], typing_extensions.Literal["MobileFirst"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["QuestionDescriptionOption"]) -> typing.Union[MetaOapg.properties.QuestionDescriptionOption, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["TextPosition"]) -> typing.Union[MetaOapg.properties.TextPosition, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ChoiceColumnWidth"]) -> typing.Union[MetaOapg.properties.ChoiceColumnWidth, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["RepeatHeaders"]) -> typing.Union[MetaOapg.properties.RepeatHeaders, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["WhiteSpace"]) -> typing.Union[MetaOapg.properties.WhiteSpace, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LabelPosition"]) -> typing.Union[MetaOapg.properties.LabelPosition, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["NumColumns"]) -> typing.Union[MetaOapg.properties.NumColumns, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["MobileFirst"]) -> typing.Union[MetaOapg.properties.MobileFirst, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["QuestionDescriptionOption"], typing_extensions.Literal["TextPosition"], typing_extensions.Literal["ChoiceColumnWidth"], typing_extensions.Literal["RepeatHeaders"], typing_extensions.Literal["WhiteSpace"], typing_extensions.Literal["LabelPosition"], typing_extensions.Literal["NumColumns"], typing_extensions.Literal["MobileFirst"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        QuestionDescriptionOption: typing.Union[MetaOapg.properties.QuestionDescriptionOption, str, schemas.Unset] = schemas.unset,
        TextPosition: typing.Union[MetaOapg.properties.TextPosition, str, schemas.Unset] = schemas.unset,
        ChoiceColumnWidth: typing.Union[MetaOapg.properties.ChoiceColumnWidth, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        RepeatHeaders: typing.Union[MetaOapg.properties.RepeatHeaders, str, schemas.Unset] = schemas.unset,
        WhiteSpace: typing.Union[MetaOapg.properties.WhiteSpace, str, schemas.Unset] = schemas.unset,
        LabelPosition: typing.Union[MetaOapg.properties.LabelPosition, str, schemas.Unset] = schemas.unset,
        NumColumns: typing.Union[MetaOapg.properties.NumColumns, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        MobileFirst: typing.Union[MetaOapg.properties.MobileFirst, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'QuestionConfiguration':
        return super().__new__(
            cls,
            *args,
            QuestionDescriptionOption=QuestionDescriptionOption,
            TextPosition=TextPosition,
            ChoiceColumnWidth=ChoiceColumnWidth,
            RepeatHeaders=RepeatHeaders,
            WhiteSpace=WhiteSpace,
            LabelPosition=LabelPosition,
            NumColumns=NumColumns,
            MobileFirst=MobileFirst,
            _configuration=_configuration,
            **kwargs,
        )
