# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class QuestionSelector(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Question selector.
    """
    
    @schemas.classproperty
    def BIPOLAR(cls):
        return cls("Bipolar")
    
    @schemas.classproperty
    def BROWSER(cls):
        return cls("Browser")
    
    @schemas.classproperty
    def CAPTCHA(cls):
        return cls("Captcha")
    
    @schemas.classproperty
    def COMPACT_VIEW(cls):
        return cls("CompactView")
    
    @schemas.classproperty
    def CS(cls):
        return cls("CS")
    
    @schemas.classproperty
    def D(cls):
        return cls("D")
    
    @schemas.classproperty
    def DL(cls):
        return cls("DL")
    
    @schemas.classproperty
    def DND(cls):
        return cls("DND")
    
    @schemas.classproperty
    def DRAG_AND_DROP(cls):
        return cls("DragAndDrop")
    
    @schemas.classproperty
    def ESTB(cls):
        return cls("ESTB")
    
    @schemas.classproperty
    def FORM(cls):
        return cls("FORM")
    
    @schemas.classproperty
    def FILE_UPLOAD(cls):
        return cls("FileUpload")
    
    @schemas.classproperty
    def GRB(cls):
        return cls("GRB")
    
    @schemas.classproperty
    def HBAR(cls):
        return cls("HBAR")
    
    @schemas.classproperty
    def HR(cls):
        return cls("HR")
    
    @schemas.classproperty
    def HSLIDER(cls):
        return cls("HSLIDER")
    
    @schemas.classproperty
    def I(cls):
        return cls("I")
    
    @schemas.classproperty
    def IMAGE(cls):
        return cls("Image")
    
    @schemas.classproperty
    def LIKE_DISLIKE(cls):
        return cls("LikeDislike")
    
    @schemas.classproperty
    def LIKERT(cls):
        return cls("Likert")
    
    @schemas.classproperty
    def MACOL(cls):
        return cls("MACOL")
    
    @schemas.classproperty
    def MAHR(cls):
        return cls("MAHR")
    
    @schemas.classproperty
    def MAVR(cls):
        return cls("MAVR")
    
    @schemas.classproperty
    def ML(cls):
        return cls("ML")
    
    @schemas.classproperty
    def MSB(cls):
        return cls("MSB")
    
    @schemas.classproperty
    def MAX_DIFF(cls):
        return cls("MaxDiff")
    
    @schemas.classproperty
    def NPS(cls):
        return cls("NPS")
    
    @schemas.classproperty
    def OH(cls):
        return cls("OH")
    
    @schemas.classproperty
    def ON_OFF(cls):
        return cls("OnOff")
    
    @schemas.classproperty
    def POS(cls):
        return cls("POS")
    
    @schemas.classproperty
    def PTB(cls):
        return cls("PTB")
    
    @schemas.classproperty
    def PW(cls):
        return cls("PW")
    
    @schemas.classproperty
    def PAGE_TIMER(cls):
        return cls("PageTimer")
    
    @schemas.classproperty
    def PROFILE(cls):
        return cls("Profile")
    
    @schemas.classproperty
    def RB(cls):
        return cls("RB")
    
    @schemas.classproperty
    def RO(cls):
        return cls("RO")
    
    @schemas.classproperty
    def SACOL(cls):
        return cls("SACOL")
    
    @schemas.classproperty
    def SAHR(cls):
        return cls("SAHR")
    
    @schemas.classproperty
    def SAVR(cls):
        return cls("SAVR")
    
    @schemas.classproperty
    def SB(cls):
        return cls("SB")
    
    @schemas.classproperty
    def SBSMATRIX(cls):
        return cls("SBSMatrix")
    
    @schemas.classproperty
    def SL(cls):
        return cls("SL")
    
    @schemas.classproperty
    def STAR(cls):
        return cls("STAR")
    
    @schemas.classproperty
    def SCREEN_CAPTURE(cls):
        return cls("ScreenCapture")
    
    @schemas.classproperty
    def SEARCH_ONLY(cls):
        return cls("SearchOnly")
    
    @schemas.classproperty
    def SIGNATURE(cls):
        return cls("Signature")
    
    @schemas.classproperty
    def TA(cls):
        return cls("TA")
    
    @schemas.classproperty
    def TB(cls):
        return cls("TB")
    
    @schemas.classproperty
    def TBELOW(cls):
        return cls("TBelow")
    
    @schemas.classproperty
    def TE(cls):
        return cls("TE")
    
    @schemas.classproperty
    def TL(cls):
        return cls("TL")
    
    @schemas.classproperty
    def TRIGHT(cls):
        return cls("TRight")
    
    @schemas.classproperty
    def TEXT(cls):
        return cls("Text")
    
    @schemas.classproperty
    def V1(cls):
        return cls("V1")
    
    @schemas.classproperty
    def V2(cls):
        return cls("V2")
    
    @schemas.classproperty
    def VR(cls):
        return cls("VR")
    
    @schemas.classproperty
    def VRTL(cls):
        return cls("VRTL")
    
    @schemas.classproperty
    def WTXB(cls):
        return cls("WTXB")
