# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class QuotaSchedule(
    schemas.ComposedSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        
        class one_of_0(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                required = {
                    "QuotaPeriodLength",
                    "QuotaStart",
                    "QuotaNumPeriods",
                }
                
                class properties:
                    
                    
                    class QuotaStart(
                        schemas.StrSchema
                    ):
                        pass
                
                    @staticmethod
                    def QuotaPeriodLength() -> typing.Type['QuotaPeriodLength']:
                        return QuotaPeriodLength
                
                    @staticmethod
                    def QuotaNumPeriods() -> typing.Type['QuotaPeriodLength']:
                        return QuotaPeriodLength
                
                    @staticmethod
                    def StartTimezone() -> typing.Type['TimeZone']:
                        return TimeZone
                    
                    
                    class QuotaCounts(
                        schemas.ListSchema
                    ):
                    
                    
                        class MetaOapg:
                            items = schemas.IntSchema
                    
                        def __new__(
                            cls,
                            arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'QuotaCounts':
                            return super().__new__(
                                cls,
                                arg,
                                _configuration=_configuration,
                            )
                    
                        def __getitem__(self, i: int) -> MetaOapg.items:
                            return super().__getitem__(i)
                    __annotations__ = {
                        "QuotaStart": QuotaStart,
                        "QuotaPeriodLength": QuotaPeriodLength,
                        "QuotaNumPeriods": QuotaNumPeriods,
                        "StartTimezone": StartTimezone,
                        "QuotaCounts": QuotaCounts,
                    }
            
            QuotaPeriodLength: 'QuotaPeriodLength'
            QuotaStart: MetaOapg.properties.QuotaStart
            QuotaNumPeriods: 'QuotaPeriodLength'
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["QuotaStart"]) -> MetaOapg.properties.QuotaStart: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["QuotaPeriodLength"]) -> 'QuotaPeriodLength': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["QuotaNumPeriods"]) -> 'QuotaPeriodLength': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["StartTimezone"]) -> 'TimeZone': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["QuotaCounts"]) -> MetaOapg.properties.QuotaCounts: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["QuotaStart", "QuotaPeriodLength", "QuotaNumPeriods", "StartTimezone", "QuotaCounts", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["QuotaStart"]) -> MetaOapg.properties.QuotaStart: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["QuotaPeriodLength"]) -> 'QuotaPeriodLength': ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["QuotaNumPeriods"]) -> 'QuotaPeriodLength': ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["StartTimezone"]) -> typing.Union['TimeZone', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["QuotaCounts"]) -> typing.Union[MetaOapg.properties.QuotaCounts, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["QuotaStart", "QuotaPeriodLength", "QuotaNumPeriods", "StartTimezone", "QuotaCounts", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *args: typing.Union[dict, frozendict.frozendict, ],
                QuotaPeriodLength: 'QuotaPeriodLength',
                QuotaStart: typing.Union[MetaOapg.properties.QuotaStart, str, ],
                QuotaNumPeriods: 'QuotaPeriodLength',
                StartTimezone: typing.Union['TimeZone', schemas.Unset] = schemas.unset,
                QuotaCounts: typing.Union[MetaOapg.properties.QuotaCounts, list, tuple, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'one_of_0':
                return super().__new__(
                    cls,
                    *args,
                    QuotaPeriodLength=QuotaPeriodLength,
                    QuotaStart=QuotaStart,
                    QuotaNumPeriods=QuotaNumPeriods,
                    StartTimezone=StartTimezone,
                    QuotaCounts=QuotaCounts,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def one_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                cls.one_of_0,
            ]


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'QuotaSchedule':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )

from qualtrics_survey_python_sdk.model.quota_period_length import QuotaPeriodLength
from qualtrics_survey_python_sdk.model.time_zone import TimeZone
