# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class ScoringDefinition(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "DefaultScoringCategory",
            "AutoScoringCategory",
            "ScoringCategoryGroups",
            "ScoringSummaryCategory",
            "ScoringCategories",
            "ScoringSummaryAfterSurvey",
            "ScoringSummaryAfterQuestions",
        }
        
        class properties:
        
            @staticmethod
            def ScoringCategories() -> typing.Type['ScoringDefinitionScoringCategories']:
                return ScoringDefinitionScoringCategories
        
            @staticmethod
            def ScoringCategoryGroups() -> typing.Type['ScoringDefinitionScoringCategoryGroups']:
                return ScoringDefinitionScoringCategoryGroups
        
            @staticmethod
            def ScoringSummaryCategory() -> typing.Type['ScoringID']:
                return ScoringID
            ScoringSummaryAfterQuestions = schemas.BoolSchema
            ScoringSummaryAfterSurvey = schemas.BoolSchema
        
            @staticmethod
            def DefaultScoringCategory() -> typing.Type['ScoringID']:
                return ScoringID
            AutoScoringCategory = schemas.StrSchema
            __annotations__ = {
                "ScoringCategories": ScoringCategories,
                "ScoringCategoryGroups": ScoringCategoryGroups,
                "ScoringSummaryCategory": ScoringSummaryCategory,
                "ScoringSummaryAfterQuestions": ScoringSummaryAfterQuestions,
                "ScoringSummaryAfterSurvey": ScoringSummaryAfterSurvey,
                "DefaultScoringCategory": DefaultScoringCategory,
                "AutoScoringCategory": AutoScoringCategory,
            }
        additional_properties = schemas.AnyTypeSchema
    
    DefaultScoringCategory: 'ScoringID'
    AutoScoringCategory: MetaOapg.properties.AutoScoringCategory
    ScoringCategoryGroups: 'ScoringDefinitionScoringCategoryGroups'
    ScoringSummaryCategory: 'ScoringID'
    ScoringCategories: 'ScoringDefinitionScoringCategories'
    ScoringSummaryAfterSurvey: MetaOapg.properties.ScoringSummaryAfterSurvey
    ScoringSummaryAfterQuestions: MetaOapg.properties.ScoringSummaryAfterQuestions
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["DefaultScoringCategory"]) -> 'ScoringID': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["AutoScoringCategory"]) -> MetaOapg.properties.AutoScoringCategory: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ScoringCategoryGroups"]) -> 'ScoringDefinitionScoringCategoryGroups': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ScoringSummaryCategory"]) -> 'ScoringID': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ScoringCategories"]) -> 'ScoringDefinitionScoringCategories': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ScoringSummaryAfterSurvey"]) -> MetaOapg.properties.ScoringSummaryAfterSurvey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ScoringSummaryAfterQuestions"]) -> MetaOapg.properties.ScoringSummaryAfterQuestions: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["DefaultScoringCategory"], typing_extensions.Literal["AutoScoringCategory"], typing_extensions.Literal["ScoringCategoryGroups"], typing_extensions.Literal["ScoringSummaryCategory"], typing_extensions.Literal["ScoringCategories"], typing_extensions.Literal["ScoringSummaryAfterSurvey"], typing_extensions.Literal["ScoringSummaryAfterQuestions"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["DefaultScoringCategory"]) -> 'ScoringID': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["AutoScoringCategory"]) -> MetaOapg.properties.AutoScoringCategory: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ScoringCategoryGroups"]) -> 'ScoringDefinitionScoringCategoryGroups': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ScoringSummaryCategory"]) -> 'ScoringID': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ScoringCategories"]) -> 'ScoringDefinitionScoringCategories': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ScoringSummaryAfterSurvey"]) -> MetaOapg.properties.ScoringSummaryAfterSurvey: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ScoringSummaryAfterQuestions"]) -> MetaOapg.properties.ScoringSummaryAfterQuestions: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["DefaultScoringCategory"], typing_extensions.Literal["AutoScoringCategory"], typing_extensions.Literal["ScoringCategoryGroups"], typing_extensions.Literal["ScoringSummaryCategory"], typing_extensions.Literal["ScoringCategories"], typing_extensions.Literal["ScoringSummaryAfterSurvey"], typing_extensions.Literal["ScoringSummaryAfterQuestions"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        DefaultScoringCategory: 'ScoringID',
        AutoScoringCategory: typing.Union[MetaOapg.properties.AutoScoringCategory, str, ],
        ScoringCategoryGroups: 'ScoringDefinitionScoringCategoryGroups',
        ScoringSummaryCategory: 'ScoringID',
        ScoringCategories: 'ScoringDefinitionScoringCategories',
        ScoringSummaryAfterSurvey: typing.Union[MetaOapg.properties.ScoringSummaryAfterSurvey, bool, ],
        ScoringSummaryAfterQuestions: typing.Union[MetaOapg.properties.ScoringSummaryAfterQuestions, bool, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'ScoringDefinition':
        return super().__new__(
            cls,
            *args,
            DefaultScoringCategory=DefaultScoringCategory,
            AutoScoringCategory=AutoScoringCategory,
            ScoringCategoryGroups=ScoringCategoryGroups,
            ScoringSummaryCategory=ScoringSummaryCategory,
            ScoringCategories=ScoringCategories,
            ScoringSummaryAfterSurvey=ScoringSummaryAfterSurvey,
            ScoringSummaryAfterQuestions=ScoringSummaryAfterQuestions,
            _configuration=_configuration,
            **kwargs,
        )

from qualtrics_survey_python_sdk.model.scoring_definition_scoring_categories import ScoringDefinitionScoringCategories
from qualtrics_survey_python_sdk.model.scoring_definition_scoring_category_groups import ScoringDefinitionScoringCategoryGroups
from qualtrics_survey_python_sdk.model.scoring_id import ScoringID
