# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class SurveyTermination(
    schemas.EnumBase,
    schemas.StrBase,
    schemas.NoneBase,
    schemas.Schema,
    schemas.NoneStrMixin
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    End of survey action such as showing respondents a response summary. See `EOSMessageLibrary`, `EOSMessage`, `ResponseSummary`, and `EOSRedirectURL`.
    """


    class MetaOapg:
        enum_value_to_name = {
            "DefaultMessage": "DEFAULT_MESSAGE",
            "DisplayMessage": "DISPLAY_MESSAGE",
            "DisplayResult": "DISPLAY_RESULT",
            "ResponseSummary": "RESPONSE_SUMMARY",
            "Redirect": "REDIRECT",
        }
    
    @schemas.classproperty
    def DEFAULT_MESSAGE(cls):
        return cls("DefaultMessage")
    
    @schemas.classproperty
    def DISPLAY_MESSAGE(cls):
        return cls("DisplayMessage")
    
    @schemas.classproperty
    def DISPLAY_RESULT(cls):
        return cls("DisplayResult")
    
    @schemas.classproperty
    def RESPONSE_SUMMARY(cls):
        return cls("ResponseSummary")
    
    @schemas.classproperty
    def REDIRECT(cls):
        return cls("Redirect")


    def __new__(
        cls,
        *args: typing.Union[None, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'SurveyTermination':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )
