# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from qualtrics_survey_python_sdk import schemas  # noqa: F401


class UpdateMetadataRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            SurveyName = schemas.StrSchema
            
            
            class SurveyDescription(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'SurveyDescription':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def SurveyStatus() -> typing.Type['SurveyStatusPutMetadata']:
                return SurveyStatusPutMetadata
            
            
            class SurveyStartDate(
                schemas.StrSchema
            ):
                pass
            
            
            class SurveyExpirationDate(
                schemas.StrSchema
            ):
                pass
            __annotations__ = {
                "SurveyName": SurveyName,
                "SurveyDescription": SurveyDescription,
                "SurveyStatus": SurveyStatus,
                "SurveyStartDate": SurveyStartDate,
                "SurveyExpirationDate": SurveyExpirationDate,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SurveyName"]) -> MetaOapg.properties.SurveyName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SurveyDescription"]) -> MetaOapg.properties.SurveyDescription: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SurveyStatus"]) -> 'SurveyStatusPutMetadata': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SurveyStartDate"]) -> MetaOapg.properties.SurveyStartDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SurveyExpirationDate"]) -> MetaOapg.properties.SurveyExpirationDate: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["SurveyName", "SurveyDescription", "SurveyStatus", "SurveyStartDate", "SurveyExpirationDate", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SurveyName"]) -> typing.Union[MetaOapg.properties.SurveyName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SurveyDescription"]) -> typing.Union[MetaOapg.properties.SurveyDescription, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SurveyStatus"]) -> typing.Union['SurveyStatusPutMetadata', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SurveyStartDate"]) -> typing.Union[MetaOapg.properties.SurveyStartDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SurveyExpirationDate"]) -> typing.Union[MetaOapg.properties.SurveyExpirationDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["SurveyName", "SurveyDescription", "SurveyStatus", "SurveyStartDate", "SurveyExpirationDate", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        SurveyName: typing.Union[MetaOapg.properties.SurveyName, str, schemas.Unset] = schemas.unset,
        SurveyDescription: typing.Union[MetaOapg.properties.SurveyDescription, None, str, schemas.Unset] = schemas.unset,
        SurveyStatus: typing.Union['SurveyStatusPutMetadata', schemas.Unset] = schemas.unset,
        SurveyStartDate: typing.Union[MetaOapg.properties.SurveyStartDate, str, schemas.Unset] = schemas.unset,
        SurveyExpirationDate: typing.Union[MetaOapg.properties.SurveyExpirationDate, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UpdateMetadataRequest':
        return super().__new__(
            cls,
            *args,
            SurveyName=SurveyName,
            SurveyDescription=SurveyDescription,
            SurveyStatus=SurveyStatus,
            SurveyStartDate=SurveyStartDate,
            SurveyExpirationDate=SurveyExpirationDate,
            _configuration=_configuration,
            **kwargs,
        )

from qualtrics_survey_python_sdk.model.survey_status_put_metadata import SurveyStatusPutMetadata
