# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_quotas.post import CreateNewQuotaRaw
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_quotagroups.post import CreateQuotaGroupRaw
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_quotas_quota_id.delete import DeleteQuotaRaw
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_quotas.get import GetAllRaw
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_quotas_quota_id.get import GetDefinitionRaw
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_quotagroups_quota_group_id.get import GetQuotaGroupDefinitionRaw
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_quotagroups.get import ListQuotaGroupsRaw
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_quotagroups_quota_group_id.delete import RemoveQuotaGroupRaw
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_quotas_quota_id.put import UpdateDefinitionRaw
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_quotagroups_quota_group_id.put import UpdateQuotaGroupDefinitionRaw


class SurveyQuotasApiRaw(
    CreateNewQuotaRaw,
    CreateQuotaGroupRaw,
    DeleteQuotaRaw,
    GetAllRaw,
    GetDefinitionRaw,
    GetQuotaGroupDefinitionRaw,
    ListQuotaGroupsRaw,
    RemoveQuotaGroupRaw,
    UpdateDefinitionRaw,
    UpdateQuotaGroupDefinitionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
