# coding: utf-8

"""
    Qualtrics Survey API

    The Qualtrics Survey endpoints give you access to the structure of the surveys you create.   Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints.   Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

    The version of the OpenAPI document: 3.0.0
    Created by: https://www.qualtrics.com/support/
"""

from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_questions.post import CreateNewQuestion
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_questions_question_id.get import GetDefinition
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_questions.get import GetList
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_questions_question_id.delete import RemoveQuestion
from qualtrics_survey_python_sdk.paths.survey_definitions_survey_id_questions_question_id.put import UpdateDefinition
from qualtrics_survey_python_sdk.apis.tags.survey_questions_api_raw import SurveyQuestionsApiRaw


class SurveyQuestionsApi(
    CreateNewQuestion,
    GetDefinition,
    GetList,
    RemoveQuestion,
    UpdateDefinition,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SurveyQuestionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SurveyQuestionsApiRaw(api_client)
